In [1]:
import pandas as pd
pd.set_option('display.max_rows', 20000)
pd.set_option('display.max_columns', 20000)

In [2]:
### Loading CLeaned Dataset
import pandas as pd
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

In [10]:
df = pd.read_csv('Cleaned_df.csv') 

In [11]:
df.head()

id                                     title  vote_average  popularity  \
0   19995                                    Avatar           7.2  150.437577   
1     285  Pirates of the Caribbean: At World's End           6.9  139.082615   
2  206647                                   Spectre           6.3  107.376788   
3   49026                     The Dark Knight Rises           7.6  112.312950   
4   49529                               John Carter           6.1   43.926995   

                                                tags  
0  samworthington zoesaldana sigourneyweaver step...  
1  johnnydepp orlandobloom keiraknightley stellan...  
2  danielcraig christophwaltz laseydoux ralphfien...  
3  christianbale michaelcaine garyoldman annehath...  
4  taylorkitsch lynncollins samanthamorton willem...

In [12]:
df.title.unique()

array(['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre',
       'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled',
       'Avengers: Age of Ultron',
       'Harry Potter and the Half-Blood Prince',
       'Batman v Superman: Dawn of Justice', 'Superman Returns',
       'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest",
       'The Lone Ranger', 'Man of Steel',
       'The Chronicles of Narnia: Prince Caspian', 'The Avengers',
       'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3',
       'The Hobbit: The Battle of the Five Armies',
       'The Amazing Spider-Man', 'Robin Hood',
       'The Hobbit: The Desolation of Smaug', 'The Golden Compass',
       'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship',
       'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3',
       'Alice in Wonderland', 'X-Men: The Last Stand',
       'Monsters University', 'Transformers: Revenge of the Fallen',
       'Transformer

limit_output extension: Maximum message size of 100000 exceeded with 104202 characters

In [13]:
df.vote_average.unique()

array([ 7.2,  6.9,  6.3,  7.6,  6.1,  5.9,  7.4,  7.3,  5.7,  5.4,  7. ,
        6.5,  6.4,  6.2,  7.1,  5.8,  6.6,  7.5,  5.5,  6.7,  6.8,  6. ,
        5.1,  7.8,  5.6,  5.2,  8.2,  7.7,  5.3,  8. ,  4.8,  4.9,  7.9,
        8.1,  4.7,  5. ,  4.2,  4.4,  4.1,  3.7,  3.6,  3. ,  3.9,  4.3,
        4.5,  3.4,  4.6,  8.3,  3.5,  4. ,  2.3,  3.2,  0. ,  3.8,  2.9,
        8.5,  1.9,  3.1,  3.3,  2.2,  0.5,  9.3,  8.4,  2.7, 10. ,  1. ,
        2. ,  2.8,  9.5,  2.6,  2.4])

In [14]:
df.popularity.head()

0    150.437577
1    139.082615
2    107.376788
3    112.312950
4     43.926995
Name: popularity, dtype: float64

In [15]:
df.isnull().sum()

id              0
title           0
vote_average    0
popularity      0
tags            0
dtype: int64

## Content Based Recommender System

### 1. CountVectorizer (Bag of Words)

In [16]:
# Removing Stop-words
from sklearn.feature_extraction.text import CountVectorizer
countVec = CountVectorizer(max_features=10000)

In [17]:
# Tags of Movies Convert in Vectors
Vectors = countVec.fit_transform(df['tags']).toarray()

In [18]:
Vectors[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [19]:
###### COSING SIMILARITY BETWEEN COUNT VECTORS #########
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(Vectors)

In [20]:
def get_title_from_index(index):
    return df[df.index == index]["title"].values[0]
def get_index_from_title(title):
    return df[df.title == title].index[0]

In [21]:
### GENERATING Recommended MOVIES TITLES

user_liked_movie = 'The Avengers'

movie_index = get_index_from_title(user_liked_movie)

similar_movies = list(enumerate(similarity[movie_index]))

sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)[1:11]

print(f'------ Top 10 Recommended Movies For {user_liked_movie}------')
for i in sorted_similar_movies:
    print(get_title_from_index(i[0]))

------ Top 10 Recommended Movies For The Avengers------
Avengers: Age of Ultron
Iron Man 3
Captain America: Civil War
Captain America: The Winter Soldier
Captain America: The First Avenger
Iron Man 2
Iron Man
Ant-Man
Thor: The Dark World
The Incredible Hulk


In [22]:
###### SORTING MOVIES BASED ON POPULARITY ##########
user_liked_movie = "Pirates of the Caribbean: At World's End"

movie_index = get_index_from_title(user_liked_movie)

similar_movies = list(enumerate(similarity[movie_index]))

sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)[1:11]

sort_by_average_vote = sorted(sorted_similar_movies,key=lambda x:df["popularity"][x[0]],reverse=True)

print(f'------ Top 10 Recommended Movies For {user_liked_movie}------')
for i in sort_by_average_vote:
    print(get_title_from_index(i[0]))

------ Top 10 Recommended Movies For Pirates of the Caribbean: At World's End------
Pirates of the Caribbean: The Curse of the Black Pearl
Pirates of the Caribbean: Dead Man's Chest
Pirates of the Caribbean: On Stranger Tides
Thor
Life of Pi
Independence Day: Resurgence
Waterworld
Into the Blue
20,000 Leagues Under the Sea
The Black Hole


### 2. TF-IDF 

In [23]:
# Removing Stop-words
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfVec = TfidfVectorizer(max_features=10000)

In [24]:
# Tags of Movies Convert in Vectors
tfidfVectors = tfidfVec.fit_transform(df['tags']).toarray()

In [25]:
tfidfVectors[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

limit_output extension: Maximum message size of 100000 exceeded with 134000 characters

In [26]:
###### COSING SIMILARITY BETWEEN COUNT VECTORS #########
from sklearn.metrics.pairwise import cosine_similarity
similarity_tf = cosine_similarity(tfidfVectors)

In [27]:
###### SORTING MOVIES BASED ON popularity #########
user_liked_movie = "Pirates of the Caribbean: At World's End"

movie_index = get_index_from_title(user_liked_movie)

similar_movies = list(enumerate(similarity_tf[movie_index]))

sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)[1:11]

sort_by_average_vote = sorted(sorted_similar_movies,key=lambda x:df["popularity"][x[0]],reverse=True)

print(f'------ Top 10 Recommended Movies For {user_liked_movie}------')
for i in sort_by_average_vote:
    print(get_title_from_index(i[0]))

------ Top 10 Recommended Movies For Pirates of the Caribbean: At World's End------
Pirates of the Caribbean: The Curse of the Black Pearl
Pirates of the Caribbean: Dead Man's Chest
Pirates of the Caribbean: On Stranger Tides
Life of Pi
Waterworld
The Pirates! In an Adventure with Scientists!
Nim's Island
20,000 Leagues Under the Sea
Moby Dick
The Pirate


### 3. sigmoid_kernel (Instead of Cosine Similarity)


In [29]:
from sklearn.metrics.pairwise import sigmoid_kernel

# Compute the sigmoid kernel
sig = sigmoid_kernel(tfidfVectors, tfidfVectors)

In [30]:
sig[0]

array([0.76163615, 0.7615948 , 0.76159453, 0.76159482, 0.76159754,
       0.76159586, 0.76159416, 0.76159663, 0.76159471, 0.76159472,
       0.76159499, 0.76159501, 0.76159483, 0.7615944 , 0.76159511,
       0.76159454, 0.76159473, 0.76159628, 0.76159601, 0.76159504,
       0.76159459, 0.76159521, 0.76159465, 0.76159498, 0.76159478,
       0.76159558, 0.76159658, 0.76159728, 0.76159546, 0.761595  ,
       0.76159498, 0.76159681, 0.76159525, 0.76159485, 0.76159416,
       0.76159479, 0.76159762, 0.7615952 , 0.76159463, 0.76159478,
       0.76159503, 0.76159617, 0.76159416, 0.76159658, 0.76159615,
       0.76159589, 0.76159638, 0.76159923, 0.76159502, 0.76159504,
       0.76159505, 0.76159493, 0.76159761, 0.76159443, 0.76159443,
       0.76159519, 0.76159711, 0.7615949 , 0.76159443, 0.76159538,
       0.76159463, 0.7615977 , 0.76159463, 0.76159532, 0.76159444,
       0.76159426, 0.76159435, 0.76159668, 0.76159601, 0.76159464,
       0.76159473, 0.76159487, 0.76159508, 0.76159453, 0.76159

In [48]:
###### SORTING MOVIES BASED ON popularity #########

### USER INPUT MOVIE
user_liked_movie = "Pirates of the Caribbean: At World's End"

### MOVIE INDEX
movie_index = get_index_from_title(user_liked_movie)


###  PAIRWISE SIMILARITY SCORES
similar_movies = list(enumerate(sig[movie_index]))

### SORT THE MOVIES AND EXTRACT TOP 10 MOVIES
sorted_similar_movies = sorted(similar_movies,key=lambda x:x[1],reverse=True)[1:11]

sort_by_average_vote = sorted(sorted_similar_movies,key=lambda x:df["popularity"][x[0]],reverse=True)


print(f'------ Top 10 Recommended Movies For {user_liked_movie}------')
for i in sort_by_average_vote:
    print(get_title_from_index(i[0]))

------ Top 10 Recommended Movies For Pirates of the Caribbean: At World's End------
Pirates of the Caribbean: The Curse of the Black Pearl
Pirates of the Caribbean: Dead Man's Chest
Pirates of the Caribbean: On Stranger Tides
Life of Pi
Waterworld
The Pirates! In an Adventure with Scientists!
Nim's Island
20,000 Leagues Under the Sea
Moby Dick
The Pirate


##### Both BOB and TF-IDF Gives Similar Recommendation But Observing Closely TF-IDF GIves Better.


In [28]:
import pickle

pickle.dump(similarity_tf,open('similarity_tf.pkl','wb'))

### VISUALIZING RECOMMENDATIONS

In [88]:
def fetch_movies_poster(movieID):
    response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key=c0bda0be71f7815fd6ba2eb5f5c86fd8'.format(movieID) )
    data = response.json()
    posterPath = "http://image.tmdb.org/t/p/w500" + data['poster_path']
    return posterPath

def getRecommended_movies_name(xMovie):
    # Get Index of given Movie
    movie_index = df[df["title"].str.lower() == xMovie.lower()].index[0]
    distances = similarity_tf[movie_index]
    listofMovies = sorted(list(enumerate(distances)), reverse=True, key=lambda x:x[1])[1:6]
    listofMovies = sorted(listofMovies,key=lambda x:df["popularity"][x[0]],reverse=True)

    recomended_movies = []
    movies_poster = []
    for i in listofMovies:
        recomended_movies.append(df.iloc[i[0]]["title"])
        # API required to fetch the poster_path
        movies_poster.append(fetch_movies_poster(df.iloc[i[0]]["id"]) )
        
    return recomended_movies, movies_poster

from IPython.display import Image, HTML, display
def show_poster(sel_movie, mov_name, posterPath):
    display(HTML(f"""<div style="font-size:24px; font-weight:Bold; color:#fff; text-align:center; padding-top:8px; height:12%; width: 100%; border:1px solid #ccc; border-radius:10px; margin-top:10px; background-color:green;">{sel_movie}</div>
                   <table>
                    <tr>
                        <td><img src={posterPath[0]} style='border-radius:10px; width:575px; height:300px;'></td>
                        <td><img src={posterPath[1]} style='border-radius:10px; width:575px; height:300px;'></td>
                        <td><img src={posterPath[2]} style='border-radius:10px; width:575px; height:300px;'></td>
                        <td><img src={posterPath[3]} style='border-radius:10px; width:575px; height:300px;'></td>
                        <td><img src={posterPath[4]} style='border-radius:10px; width:575px; height:300px;'></td>
                    </tr>
                    <tr>
                        <td><p style="text-align:center; font-size:14px; font-weight:bold">{mov_name[0]}</p></td>
                        <td><p style="text-align:center; font-size:14px; font-weight:bold">{mov_name[1]}</p></td>
                        <td><p style="text-align:center; font-size:14px; font-weight:bold">{mov_name[2]}</p></td>
                        <td><p style="text-align:center; font-size:14px; font-weight:bold">{mov_name[3]}</p></td>
                        <td><p style="text-align:center; font-size:14px; font-weight:bold">{mov_name[4]}</p></td>
                    </tr>
                   </table>""") )

#### TF-IDF

In [91]:
# Show the Recommended Name and Poster of Movies in List
import requests
movies_list = {"Avatar","The Avengers","Pirates of the Caribbean: At World's End"}

for x in movies_list:
    names, poster = getRecommended_movies_name(x)
    show_poster(x, names, poster)